// data.jsx — Recipe data and helpers
// Real recipe data per brief (C1 LEICA-LIKE from X-H2 PTP read).
// Other slots are plausible user-named recipes referencing film stocks.

const RECIPES = [
  {
    slot: 'C1',
    name: 'LEICA-LIKE',
    sim: 'Pro Neg Hi',
    pills: ['DR400%', 'GRAIN ST/L', 'CC STRONG', 'HL −1'],
    description: 'A muted, slightly desaturated portrait look inspired by Leica\'s classic color science. Pro Neg Hi base with strong color chrome for depth.',
    effects: {
      'Dynamic Range': 'DR400%',
      'Grain Effect': 'Strong Large',
      'Color Chrome': 'Strong',
      'Color Chrome FX Blue': 'Weak',
      'Smooth Skin': 'Weak',
    },
    tone: {
      'Highlight Tone': '−1',
      'Shadow Tone': '0',
      'Color': '+2',
      'Sharpness': '0',
      'High ISO NR': '0',
      'Clarity': '0',
    },
    wb: {
      'White Balance': '4700K',
      'WB Shift R': '+2',
      'WB Shift B': '+2',
    },
  },
  {
    slot: 'C2',
    name: 'PORTRA 160',
    sim: 'Classic Chrome',
    pills: ['DR100%', 'GRAIN WK/S', 'CC WEAK', 'HL +1'],
    description: 'Echoes the gentle pastel palette of Kodak Portra 160 — soft skin tones, lifted highlights, the easiest look to live with.',
    effects: {
      'Dynamic Range': 'DR100%',
      'Grain Effect': 'Weak Small',
      'Color Chrome': 'Weak',
      'Color Chrome FX Blue': 'Off',
      'Smooth Skin': 'Off',
    },
    tone: {
      'Highlight Tone': '+1',
      'Shadow Tone': '−0.5',
      'Color': '0',
      'Sharpness': '−1',
      'High ISO NR': '−2',
      'Clarity': '0',
    },
    wb: {
      'White Balance': 'Auto',
      'WB Shift R': '0',
      'WB Shift B': '−1',
    },
  },
  {
    slot: 'C3',
    name: 'KODACHROME',
    sim: 'Classic Chrome',
    pills: ['DR AUTO', 'GRAIN ST/S', 'CC STRONG', 'FX BLUE STR'],
    description: 'Warm reds, deep blues, that mid-century editorial cast. Lifted shadows and red-shifted white balance for the unmistakable Kodachrome glow.',
    effects: {
      'Dynamic Range': 'DR Auto',
      'Grain Effect': 'Strong Small',
      'Color Chrome': 'Strong',
      'Color Chrome FX Blue': 'Strong',
      'Smooth Skin': 'Off',
    },
    tone: {
      'Highlight Tone': '−1',
      'Shadow Tone': '+2',
      'Color': '+4',
      'Sharpness': '+1',
      'High ISO NR': '0',
      'Clarity': '+2',
    },
    wb: {
      'White Balance': 'Daylight',
      'WB Shift R': '+1',
      'WB Shift B': '−2',
    },
  },
  {
    slot: 'C4',
    name: 'TRI-X 400',
    sim: 'Acros+R',
    pills: ['DR400%', 'GRAIN ST/L', 'CLARITY +3'],
    description: 'Pushed black-and-white reportage. High contrast, lifted grain, the documentary feel of TRI-X souped a stop hot.',
    effects: {
      'Dynamic Range': 'DR400%',
      'Grain Effect': 'Strong Large',
      'Color Chrome': '—',
      'Color Chrome FX Blue': '—',
      'Smooth Skin': 'Off',
    },
    tone: {
      'Highlight Tone': '+1',
      'Shadow Tone': '+2',
      'Color': '0',
      'Sharpness': '+2',
      'High ISO NR': '−4',
      'Clarity': '+3',
    },
    wb: {
      'White Balance': '5500K',
      'WB Shift R': '0',
      'WB Shift B': '0',
    },
  },
  {
    slot: 'C5',
    name: 'EKTACHROME E100',
    sim: 'Velvia',
    pills: ['DR200%', 'CC STRONG', 'COLOR +2'],
    description: 'Slide-film vibrance with a daylight-balanced bite — saturated greens and a touch of cyan in the shadows. Outdoor stock.',
    effects: {
      'Dynamic Range': 'DR200%',
      'Grain Effect': 'Off',
      'Color Chrome': 'Strong',
      'Color Chrome FX Blue': 'Strong',
      'Smooth Skin': 'Off',
    },
    tone: {
      'Highlight Tone': '0',
      'Shadow Tone': '+1',
      'Color': '+2',
      'Sharpness': '+1',
      'High ISO NR': '−2',
      'Clarity': '+1',
    },
    wb: {
      'White Balance': 'Daylight',
      'WB Shift R': '−1',
      'WB Shift B': '+1',
    },
  },
  {
    slot: 'C6',
    name: 'CINESTILL 800T',
    sim: 'Eterna',
    pills: ['DR400%', 'TUNGSTEN', 'HL −2'],
    description: 'Tungsten-balanced cinema stock. Low-contrast Eterna base, halated highlights via grain, the night-photography cult favorite.',
    effects: {
      'Dynamic Range': 'DR400%',
      'Grain Effect': 'Weak Large',
      'Color Chrome': 'Weak',
      'Color Chrome FX Blue': 'Weak',
      'Smooth Skin': 'Off',
    },
    tone: {
      'Highlight Tone': '−2',
      'Shadow Tone': '+1',
      'Color': '+1',
      'Sharpness': '−1',
      'High ISO NR': '0',
      'Clarity': '−1',
    },
    wb: {
      'White Balance': 'Tungsten',
      'WB Shift R': '+3',
      'WB Shift B': '−4',
    },
  },
  {
    slot: 'C7',
    name: 'REALA ACE',
    sim: 'Reala Ace',
    pills: ['DR AUTO', 'CC WEAK', 'HL 0'],
    description: 'A neutral everyday recipe on the new Reala Ace simulation — accurate skin tones, gentle saturation, nothing showy.',
    effects: {
      'Dynamic Range': 'DR Auto',
      'Grain Effect': 'Weak Small',
      'Color Chrome': 'Weak',
      'Color Chrome FX Blue': 'Off',
      'Smooth Skin': 'Weak',
    },
    tone: {
      'Highlight Tone': '0',
      'Shadow Tone': '0',
      'Color': '+1',
      'Sharpness': '0',
      'High ISO NR': '−2',
      'Clarity': '0',
    },
    wb: {
      'White Balance': 'Auto',
      'WB Shift R': '0',
      'WB Shift B': '0',
    },
  },
];

// Library recipes (NOT in camera slots — saved separately)
const LIBRARY = [
  {
    id: 'lib1',
    name: 'GOLDEN HOUR',
    sim: 'Classic Chrome',
    pills: ['DR200%', 'CC STRONG', 'HL −1', 'SH +1', 'COLOR +2'],
    saved: 'May 24',
  },
  {
    id: 'lib2',
    name: 'SUMMER 84',
    sim: 'Velvia',
    pills: ['DR400%', 'GRAIN ST/L', 'CC STRONG', 'COLOR +4'],
    saved: 'May 20',
  },
  {
    id: 'lib3',
    name: 'COOL FOG',
    sim: 'Classic Neg',
    pills: ['DR400%', 'CC WEAK', 'HL +2', 'SH +1', 'COLOR −2'],
    saved: 'May 18',
  },
  {
    id: 'lib4',
    name: 'STREET MONO',
    sim: 'Acros',
    pills: ['DR400%', 'GRAIN ST/S', 'CLARITY +2'],
    saved: 'May 12',
  },
  {
    id: 'lib5',
    name: 'POLAROID 600',
    sim: 'Astia',
    pills: ['DR100%', 'GRAIN WK/L', 'HL +2', 'COLOR −1'],
    saved: 'May 09',
  },
  {
    id: 'lib6',
    name: 'OVERCAST PORTRAIT',
    sim: 'Pro Neg Std',
    pills: ['DR200%', 'CC WEAK', 'SMOOTH SKIN WK', 'HL +1'],
    saved: 'May 02',
  },
];

window.RECIPES = RECIPES;
window.LIBRARY = LIBRARY;
