package com.ilfforever.fujirecipes.ui.model

object SampleData {
    val libraryGroups = listOf(
        LibraryGroupUiModel(id = "group-library", name = "Library"),
        LibraryGroupUiModel(id = "group-color", name = "Color"),
        LibraryGroupUiModel(id = "group-muted", name = "Muted"),
        LibraryGroupUiModel(id = "group-bw", name = "B&W"),
        LibraryGroupUiModel(id = "group-soft", name = "Soft"),
        LibraryGroupUiModel(id = "group-portrait", name = "Portrait"),
        LibraryGroupUiModel(id = "group-camera-saves", name = "Camera Saves"),
    )

    val slots = listOf(
        RecipeUiModel(
            slot = "C1", name = "LEICA-LIKE", sim = "Pro Neg Hi",
            pills = listOf("DR400%", "GRAIN ST/L", "CC STRONG", "HL −1"),
            description = "A muted, slightly desaturated portrait look inspired by Leica's classic color science. Pro Neg Hi base with strong color chrome for depth.",
            effects = mapOf("Dynamic Range" to "DR400%", "Grain Effect" to "Strong Large", "Color Chrome" to "Strong", "Color Chrome FX Blue" to "Weak", "Smooth Skin" to "Weak"),
            tone = mapOf("Highlight Tone" to "−1", "Shadow Tone" to "0", "Color" to "+2", "Sharpness" to "0", "High ISO NR" to "0", "Clarity" to "0"),
            wb = mapOf("White Balance" to "4700K", "WB Shift R" to "+2", "WB Shift B" to "+2"),
        ),
        RecipeUiModel(
            slot = "C2", name = "PORTRA 160", sim = "Classic Chrome",
            pills = listOf("DR100%", "GRAIN WK/S", "CC WEAK", "HL +1"),
            description = "Echoes the gentle pastel palette of Kodak Portra 160 — soft skin tones, lifted highlights, the easiest look to live with.",
            effects = mapOf("Dynamic Range" to "DR100%", "Grain Effect" to "Weak Small", "Color Chrome" to "Weak", "Color Chrome FX Blue" to "Off", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "+1", "Shadow Tone" to "−0.5", "Color" to "0", "Sharpness" to "−1", "High ISO NR" to "−2", "Clarity" to "0"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "0", "WB Shift B" to "−1"),
        ),
        RecipeUiModel(
            slot = "C3", name = "KODACHROME", sim = "Classic Chrome",
            pills = listOf("DR AUTO", "GRAIN ST/S", "CC STRONG", "FX BLUE STR"),
            description = "Warm reds, deep blues, that mid-century editorial cast. Lifted shadows and red-shifted white balance for the unmistakable Kodachrome glow.",
            effects = mapOf("Dynamic Range" to "DR Auto", "Grain Effect" to "Strong Small", "Color Chrome" to "Strong", "Color Chrome FX Blue" to "Strong", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "−1", "Shadow Tone" to "+2", "Color" to "+4", "Sharpness" to "+1", "High ISO NR" to "0", "Clarity" to "+2"),
            wb = mapOf("White Balance" to "Daylight", "WB Shift R" to "+1", "WB Shift B" to "−2"),
        ),
        RecipeUiModel(
            slot = "C4", name = "TRI-X 400", sim = "Acros+R",
            pills = listOf("DR400%", "GRAIN ST/L", "CLARITY +3"),
            description = "Pushed black-and-white reportage. High contrast, lifted grain, the documentary feel of TRI-X souped a stop hot.",
            effects = mapOf("Dynamic Range" to "DR400%", "Grain Effect" to "Strong Large", "Color Chrome" to "—", "Color Chrome FX Blue" to "—", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "+1", "Shadow Tone" to "+2", "Color" to "0", "Sharpness" to "+2", "High ISO NR" to "−4", "Clarity" to "+3"),
            wb = mapOf("White Balance" to "5500K", "WB Shift R" to "0", "WB Shift B" to "0"),
        ),
        RecipeUiModel(
            slot = "C5", name = "EKTACHROME E100", sim = "Velvia",
            pills = listOf("DR200%", "CC STRONG", "COLOR +2"),
            description = "Slide-film vibrance with a daylight-balanced bite — saturated greens and a touch of cyan in the shadows. Outdoor stock.",
            effects = mapOf("Dynamic Range" to "DR200%", "Grain Effect" to "Off", "Color Chrome" to "Strong", "Color Chrome FX Blue" to "Strong", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "0", "Shadow Tone" to "+1", "Color" to "+2", "Sharpness" to "+1", "High ISO NR" to "−2", "Clarity" to "+1"),
            wb = mapOf("White Balance" to "Daylight", "WB Shift R" to "−1", "WB Shift B" to "+1"),
        ),
        RecipeUiModel(
            slot = "C6", name = "CINESTILL 800T", sim = "Eterna",
            pills = listOf("DR400%", "TUNGSTEN", "HL −2"),
            description = "Incandescent-balanced cinema stock. Low-contrast Eterna base, halated highlights via grain, the night-photography cult favorite.",
            effects = mapOf("Dynamic Range" to "DR400%", "Grain Effect" to "Weak Large", "Color Chrome" to "Weak", "Color Chrome FX Blue" to "Weak", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "−2", "Shadow Tone" to "+1", "Color" to "+1", "Sharpness" to "−1", "High ISO NR" to "0", "Clarity" to "−1"),
            wb = mapOf("White Balance" to "Incandescent", "WB Shift R" to "+3", "WB Shift B" to "−4"),
        ),
        RecipeUiModel(
            slot = "C7", name = "REALA ACE", sim = "Reala Ace",
            pills = listOf("DR AUTO", "CC WEAK", "HL 0"),
            description = "A neutral everyday recipe on the new Reala Ace simulation — accurate skin tones, nothing showy.",
            effects = mapOf("Dynamic Range" to "DR Auto", "Grain Effect" to "Weak Small", "Color Chrome" to "Weak", "Color Chrome FX Blue" to "Off", "Smooth Skin" to "Weak"),
            tone = mapOf("Highlight Tone" to "0", "Shadow Tone" to "0", "Color" to "+1", "Sharpness" to "0", "High ISO NR" to "−2", "Clarity" to "0"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "0", "WB Shift B" to "0"),
        ),
    )

    val library = listOf(
        LibraryRecipeUiModel(
            id = "lib1",
            name = "GOLDEN HOUR",
            sim = "Classic Chrome",
            pills = listOf("DR200%", "CC STRONG", "HL −1", "SH +1", "COLOR +2"),
            saved = "May 24",
            description = "Warm late-day color with restrained contrast. Classic Chrome keeps skies and skin calm while the tone curve gives the highlights a soft glow.",
            effects = mapOf("Dynamic Range" to "DR200%", "Grain Effect" to "Weak Small", "Color Chrome" to "Strong", "Color Chrome FX Blue" to "Weak", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "−1", "Shadow Tone" to "+1", "Color" to "+2", "Sharpness" to "0", "High ISO NR" to "−2", "Clarity" to "0"),
            wb = mapOf("White Balance" to "Daylight", "WB Shift R" to "+3", "WB Shift B" to "−3"),
            groupIds = listOf("group-color"),
        ),
        LibraryRecipeUiModel(
            id = "lib2",
            name = "SUMMER 84",
            sim = "Velvia",
            pills = listOf("DR400%", "GRAIN ST/L", "CC STRONG", "COLOR +4"),
            saved = "May 20",
            description = "High-color summer slide-film energy. Velvia carries saturated greens and blues with enough grain to keep the look tactile.",
            effects = mapOf("Dynamic Range" to "DR400%", "Grain Effect" to "Strong Large", "Color Chrome" to "Strong", "Color Chrome FX Blue" to "Strong", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "−1", "Shadow Tone" to "+1", "Color" to "+4", "Sharpness" to "+1", "High ISO NR" to "−2", "Clarity" to "+1"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "+1", "WB Shift B" to "−2"),
            groupIds = listOf("group-color"),
        ),
        LibraryRecipeUiModel(
            id = "lib3",
            name = "COOL FOG",
            sim = "Classic Neg",
            pills = listOf("DR400%", "CC WEAK", "HL +2", "COLOR −2"),
            saved = "May 18",
            description = "A subdued low-saturation recipe for mist, glass, and overcast streets. Lifted highlights and cooler color keep the image airy.",
            effects = mapOf("Dynamic Range" to "DR400%", "Grain Effect" to "Weak Small", "Color Chrome" to "Weak", "Color Chrome FX Blue" to "Weak", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "+2", "Shadow Tone" to "−1", "Color" to "−2", "Sharpness" to "−1", "High ISO NR" to "−3", "Clarity" to "−2"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "−2", "WB Shift B" to "+3"),
            groupIds = listOf("group-muted"),
        ),
        LibraryRecipeUiModel(
            id = "lib4",
            name = "STREET MONO",
            sim = "Acros",
            pills = listOf("DR400%", "GRAIN ST/S", "CLARITY +2"),
            saved = "May 12",
            description = "Clean black-and-white street contrast with a tighter grain structure. Built for hard light, signage, and night walks.",
            effects = mapOf("Dynamic Range" to "DR400%", "Grain Effect" to "Strong Small", "Color Chrome" to "—", "Color Chrome FX Blue" to "—", "Smooth Skin" to "Off"),
            tone = mapOf("Highlight Tone" to "+1", "Shadow Tone" to "+2", "Color" to "0", "Sharpness" to "+2", "High ISO NR" to "−4", "Clarity" to "+2"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "0", "WB Shift B" to "0"),
            groupIds = listOf("group-bw"),
        ),
        LibraryRecipeUiModel(
            id = "lib5",
            name = "POLAROID 600",
            sim = "Astia",
            pills = listOf("DR100%", "GRAIN WK/L", "HL +2", "COLOR −1"),
            saved = "May 09",
            description = "Soft instant-film color with bright highlights and gentle skin tones. Astia keeps the contrast rounded and forgiving.",
            effects = mapOf("Dynamic Range" to "DR100%", "Grain Effect" to "Weak Large", "Color Chrome" to "Off", "Color Chrome FX Blue" to "Off", "Smooth Skin" to "Weak"),
            tone = mapOf("Highlight Tone" to "+2", "Shadow Tone" to "−1", "Color" to "−1", "Sharpness" to "−2", "High ISO NR" to "−2", "Clarity" to "−3"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "+2", "WB Shift B" to "−1"),
            groupIds = listOf("group-soft"),
        ),
        LibraryRecipeUiModel(
            id = "lib6",
            name = "OVERCAST PORTRAIT",
            sim = "Pro Neg Std",
            pills = listOf("DR200%", "CC WEAK", "SMOOTH SKIN WK", "HL +1"),
            saved = "May 02",
            description = "A quiet portrait setting for flat light. Pro Neg Std keeps faces natural while weak chrome adds just enough depth.",
            effects = mapOf("Dynamic Range" to "DR200%", "Grain Effect" to "Off", "Color Chrome" to "Weak", "Color Chrome FX Blue" to "Off", "Smooth Skin" to "Weak"),
            tone = mapOf("Highlight Tone" to "+1", "Shadow Tone" to "0", "Color" to "0", "Sharpness" to "−1", "High ISO NR" to "−1", "Clarity" to "−1"),
            wb = mapOf("White Balance" to "Auto", "WB Shift R" to "+1", "WB Shift B" to "+1"),
            groupIds = listOf("group-portrait"),
        ),
    )
}
