package com.ilfforever.fujisync.data.capability

import android.content.Context
import android.util.Log
import com.ilfforever.fujisync.domain.model.FujiPropertyCode
import org.json.JSONObject
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Fuji's per-body capability database, decoded from `XRFC.DAT` and shipped as an asset.
 *
 * The asset is generated by `tools/generate_capabilities.py` from the decoded XML in the
 * fujifilm-ptp-recipes repo; it is never hand-edited. It answers two questions per body: whether a
 * recipe property exists at all, and — for the ten properties whose legal values differ by camera
 * generation — which values that generation accepts.
 *
 * This is Fuji's client-side view. It is treated as evidence, never as proof; see [CameraCapability].
 */
@Singleton
class XrfcCapabilityTable @Inject constructor(
    private val context: Context,
) {
    private val parsed: ParsedTable? by lazy { load() }

    val version: String?
        get() = parsed?.version

    val isLoaded: Boolean
        get() = parsed != null

    /**
     * Resolves a device key to its capability record.
     *
     * Falls back through progressively looser matches so a body is not left uncovered by a
     * cosmetic difference or a firmware newer than Fuji's table:
     *  1. the key exactly as given;
     *  2. the same model and generation, ignoring case and separators;
     *  3. the same model at the highest generation the table knows that is not newer than the one
     *     asked for — a body on firmware the table predates still gets its closest known profile.
     */
    fun lookup(deviceKey: String?): TableMatch? {
        val table = parsed ?: return null
        val key = deviceKey?.trim().orEmpty()
        if (key.isEmpty()) return null

        table.devices[key]?.let { config ->
            return table.match(requestedKey = key, matchedKey = key, configName = config, exact = true)
        }

        val (model, generation) = CameraDeviceKey.split(key) ?: return null
        val canonical = CameraDeviceKey.canonicalModel(model)
        val candidates = table.devicesByModel[canonical] ?: return null

        val sameGeneration = candidates.firstOrNull { it.generation == generation }
        val best = sameGeneration
            ?: candidates.filter { it.generation <= generation }.maxByOrNull { it.generation }
            ?: candidates.minByOrNull { it.generation }
            ?: return null

        return table.match(
            requestedKey = key,
            matchedKey = best.key,
            configName = best.config,
            exact = sameGeneration != null,
        )
    }

    private fun load(): ParsedTable? = runCatching {
        val json = context.assets.open(ASSET_NAME).bufferedReader().use { it.readText() }
        parse(JSONObject(json))
    }.getOrElse {
        // A missing or malformed asset must not break connecting to a camera; the app simply
        // falls back to what the camera reports about itself.
        Log.w(TAG, "Could not load $ASSET_NAME — capability gating will use camera data only.", it)
        null
    }

    private fun parse(root: JSONObject): ParsedTable {
        val variants = parseVariants(root.optJSONObject("variants"))
        val universal = parseValueSets(root.optJSONObject("universal"))

        val devices = mutableMapOf<String, String>()
        root.optJSONObject("devices")?.let { node ->
            node.keys().forEach { key -> devices[key] = node.getString(key) }
        }

        val configs = mutableMapOf<String, Map<FujiPropertyCode, TableProperty>>()
        var grainSizeByConfig = mapOf<String, Boolean?>()
        root.optJSONObject("configs")?.let { node ->
            val grain = mutableMapOf<String, Boolean?>()
            node.keys().forEach { configName ->
                val properties = node.getJSONObject(configName).optJSONObject("properties")
                val resolved = mutableMapOf<FujiPropertyCode, TableProperty>()
                properties?.keys()?.forEach { codeKey ->
                    val code = codeKey.removePrefix("0x").toIntOrNull(16) ?: return@forEach
                    val property = FujiPropertyCode.fromCode(code) ?: return@forEach
                    val record = properties.getJSONObject(codeKey)
                    val supported = record.optBoolean("supported", false)
                    val variant = record.optString("variant").takeIf { it.isNotEmpty() }
                    val values = when {
                        !supported -> ValueSet.Unknown
                        variant != null -> variants[code]?.get(variant)?.values ?: universal[code] ?: ValueSet.Unknown
                        else -> universal[code] ?: ValueSet.Unknown
                    }
                    resolved[property] = TableProperty(supported, variant, values)
                    if (code == GRAIN_EFFECT_CODE && supported && variant != null) {
                        grain[configName] = variants[code]?.get(variant)?.grainSize
                    }
                }
                configs[configName] = resolved
            }
            grainSizeByConfig = grain
        }

        val byModel = devices.entries
            .mapNotNull { (key, config) ->
                val (model, generation) = CameraDeviceKey.split(key) ?: return@mapNotNull null
                DeviceRow(key, CameraDeviceKey.canonicalModel(model), generation, config)
            }
            .groupBy { it.canonicalModel }

        return ParsedTable(
            version = root.optString("source").takeIf { it.isNotEmpty() },
            devices = devices,
            devicesByModel = byModel,
            configs = configs,
            grainSizeByConfig = grainSizeByConfig,
        )
    }

    private fun parseVariants(node: JSONObject?): Map<Int, Map<String, VariantEntry>> {
        if (node == null) return emptyMap()
        val out = mutableMapOf<Int, Map<String, VariantEntry>>()
        node.keys().forEach { codeKey ->
            val code = codeKey.removePrefix("0x").toIntOrNull(16) ?: return@forEach
            val perVariant = node.getJSONObject(codeKey)
            val entries = mutableMapOf<String, VariantEntry>()
            perVariant.keys().forEach { variant ->
                val record = perVariant.getJSONObject(variant)
                entries[variant] = VariantEntry(
                    values = readValueSet(record),
                    grainSize = if (record.has("grainSize")) record.getBoolean("grainSize") else null,
                )
            }
            out[code] = entries
        }
        return out
    }

    private fun parseValueSets(node: JSONObject?): Map<Int, ValueSet> {
        if (node == null) return emptyMap()
        val out = mutableMapOf<Int, ValueSet>()
        node.keys().forEach { codeKey ->
            val code = codeKey.removePrefix("0x").toIntOrNull(16) ?: return@forEach
            out[code] = readValueSet(node.getJSONObject(codeKey))
        }
        return out
    }

    private fun readValueSet(record: JSONObject): ValueSet {
        record.optJSONArray("values")?.let { array ->
            val values = ArrayList<Int>(array.length())
            for (index in 0 until array.length()) values.add(array.getInt(index))
            return ValueSet.Enumerated(values)
        }
        if (record.has("min") && record.has("max")) {
            return ValueSet.Range(
                min = record.getInt("min"),
                max = record.getInt("max"),
                step = record.optInt("step", 1),
            )
        }
        return ValueSet.Unknown
    }

    private fun ParsedTable.match(
        requestedKey: String,
        matchedKey: String,
        configName: String,
        exact: Boolean,
    ): TableMatch? {
        val properties = configs[configName] ?: return null
        return TableMatch(
            requestedKey = requestedKey,
            matchedKey = matchedKey,
            configName = configName,
            exact = exact,
            properties = properties,
            grainSizeSupported = grainSizeByConfig[configName],
        )
    }

    private data class ParsedTable(
        val version: String?,
        val devices: Map<String, String>,
        val devicesByModel: Map<String, List<DeviceRow>>,
        val configs: Map<String, Map<FujiPropertyCode, TableProperty>>,
        val grainSizeByConfig: Map<String, Boolean?>,
    )

    private data class DeviceRow(
        val key: String,
        val canonicalModel: String,
        val generation: Int,
        val config: String,
    )

    private data class VariantEntry(val values: ValueSet, val grainSize: Boolean?)

    private companion object {
        const val TAG = "XrfcCapabilityTable"
        const val ASSET_NAME = "xrfc_capabilities.json"
        const val GRAIN_EFFECT_CODE = 0xD195
    }
}

/** One body's row in the capability table, after variant value lists have been resolved. */
data class TableMatch(
    val requestedKey: String,
    val matchedKey: String,
    val configName: String,
    /** False when the match fell back to a different firmware generation of the same model. */
    val exact: Boolean,
    val properties: Map<FujiPropertyCode, TableProperty>,
    val grainSizeSupported: Boolean?,
)

data class TableProperty(
    val supported: Boolean,
    val variant: String?,
    val values: ValueSet,
)
